### PR TITLE
update to 2.27.0

### PR DESCRIPTION
**Pull request by jvalli**
Update MacOS sample apps to SDK v2.27.0

### CODE REVIEW

**Review by IGitGotIt — CHANGES_REQUESTED** [review]
Any reason we want to lock the versions? Since these are sample apps , it should be any versions 
Also iOS does not have it

**Comment by jvalli** [comment]
> Any reason we want to lock the versions? Since these are sample apps , it should be any versions Also iOS does not have it

What do you mean by "lock the versions"?

**Comment by IGitGotIt** [comment]
> > Any reason we want to lock the versions? Since these are sample apps , it should be any versions Also iOS does not have it
> 
> What do you mean by "lock the versions"?

We should remove the `podfile.lock` . It locks the version for `pod install`
Not sure why we have it in first place.
I may want to try different versions of the SDK for say some issue, but then I will be locked to a particular version.

**Comment by jvalli** [comment]
> > > Any reason we want to lock the versions? Since these are sample apps , it should be any versions Also iOS does not have it
> > 
> > 
> > What do you mean by "lock the versions"?
> 
> We should remove the `podfile.lock` . It locks the version for `pod install` Not sure why we have it in first place. I may want to try different versions of the SDK for say some issue, but then I will be locked to a particular version.

Not sure why was present. I removed all files and added to gitignore.

**Review by IGitGotIt — APPROVED** [review]
+1

**Review by jintgeorge — APPROVED** [review]
LGTM

**Review by juliobecerragomez — COMMENTED** [review]
+1

**Pull request merged**
