### PR TITLE
OPENTOK-50613, OPENTOK-49633: Simple Multy-party Video Chat with Metal sample app

### PR DESCRIPTION
**Pull request by jvalli**
Simple Multy-party Video Chat with Metal sample app

### CODE REVIEW

**Comment by IGitGotIt** [comment]
Few bugs regarding subscriber windows:

1. On running the app and subscribing, the subscriber window close (red button, top left) is disabled.
2. When you disconnect the main pub window, the subscriber window/s still exists and are frozen.
3. When I kill the app, the subscriber window still remains and only a Force quit can get rid of them

**Comment by IGitGotIt** [comment]
I get this warning when building, maybe can be updated

image

**Comment by IGitGotIt** [comment]
when running bunch of linker (duplicate) warnings 

objc[98812]: Class RTCDefaultVideoDecoderFactory is implemented in both /Users/jshah2/Library/Developer/Xcode/DerivedData/Simple-Multiparty-glygygtplgduilenqceajvmfuhat/Build/Products/Debug/Simple-Multiparty.app/Contents/Frameworks/OpenTok.framework/Versions/A/OpenTok (0x112710980) and /Users/jshah2/Library/Developer/Xcode/DerivedData/Simple-Multiparty-glygygtplgduilenqceajvmfuhat/Build/Products/Debug/Simple-Multiparty.app/Contents/MacOS/Simple-Multiparty (0x10f35f6f0). One of the two will be used. Which one is undefined.

**Comment by v-kpheng** [comment]
> Few bugs regarding subscriber windows:
> 
> 1. On running the app and subscribing, the subscriber window close (red button, top left) is disabled.
> 2. When you disconnect the main pub window, the subscriber window/s still exists and are frozen.
> 3. When I kill the app, the subscriber window still remains and only a quit can get rid of them

Thanks, @IGitGotIt.

Is this something that needs fixing now?  Or, can it be fixed in a followup PR?

**Comment by jvalli** [comment]
> I get this warning when building, maybe can be updated
> 
> image

Mmmm this is weird, the deployment target is set to 12.6:
https://github.com/opentok/opentok-macos-sdk-samples/pull/4/files#diff-fe9aeb48faf1e1085f8f4c6d6b6c87a39358c36dc61d295b9fddbf4255333ab1R307

What target is giving that warning?

**Comment by jvalli** [comment]
> when running bunch of linker (duplicate) warnings
> 
> objc[98812]: Class RTCDefaultVideoDecoderFactory is implemented in both /Users/jshah2/Library/Developer/Xcode/DerivedData/Simple-Multiparty-glygygtplgduilenqceajvmfuhat/Build/Products/Debug/Simple-Multiparty.app/Contents/Frameworks/OpenTok.framework/Versions/A/OpenTok (0x112710980) and /Users/jshah2/Library/Developer/Xcode/DerivedData/Simple-Multiparty-glygygtplgduilenqceajvmfuhat/Build/Products/Debug/Simple-Multiparty.app/Contents/MacOS/Simple-Multiparty (0x10f35f6f0). One of the two will be used. Which one is undefined.

I just run `pod deintegrate` and pushed those changes, maybe that was causing duplicate warnings

**Comment by IGitGotIt** [comment]
> 

I prefer a fix , can be not that hard to do.
But if in a hurry a follow up PR also is ok (will be an irritant)

**Comment by IGitGotIt** [comment]
> > I get this warning when building, maybe can be updated
> > image
> 
> Mmmm this is weird, the deployment target is set to 12.6: https://github.com/opentok/opentok-macos-sdk-samples/pull/4/files#diff-fe9aeb48faf1e1085f8f4c6d6b6c87a39358c36dc61d295b9fddbf4255333ab1R307
> 
> What target is giving that warning?

image

**Comment by IGitGotIt** [comment]
> Few bugs regarding subscriber windows:
> 
> 1. On running the app and subscribing, the subscriber window close (red button, top left) is disabled.
> 2. When you disconnect the main pub window, the subscriber window/s still exists and are frozen.
> 3. When I kill the app, the subscriber window still remains and only a quit can get rid of them

The sub fixes are in https://github.com/opentok/opentok-macos-sdk-samples/commit/27bdb66abe8cd49e109c934df8cf56bad7dc9ec2 and the branch is https://github.com/opentok/opentok-macos-sdk-samples/tree/simple-multipart-subFixes

**Review by IGitGotIt — APPROVED** [review]
+1 

In case we need to merge subscriber fixes mention in this PR use

The sub fixes are in https://github.com/opentok/opentok-macos-sdk-samples/commit/27bdb66abe8cd49e109c934df8cf56bad7dc9ec2 and the branch is https://github.com/opentok/opentok-macos-sdk-samples/tree/simple-multipart-subFixes

**Pull request merged**
