### PR TITLE
added custom audio driver sample

### PR DESCRIPTION
**Pull request by rktalusani**

### CODE REVIEW

**Review by goncalocostamendes — APPROVED** [review]
Looks great! Should we add a README.md to the sample itself, such as https://github.com/opentok/opentok-ios-sdk-samples/tree/main/Custom-Audio-Driver ?
Nevertheless it's approved

**Comment by IGitGotIt** [comment]
Not sure , at present , of how we have organized default capturer or renderer for both video and audio in Mac. Saying that, I personally feel that custom audio and video drivers should just have the pertinent files in the sample, the rest being the default. So in this sample  having Video capturing code like OTMTLVideoRenderer etc.. (same goes for the Basic app) makes the sample feels bulky and code heavy to implement.

Trying to follow the iOS samples file organization/exposure and making it feel the same for Mac..

**Comment by v-kpheng** [comment]
> 



> Not sure , at present , of how we have organized default capturer or renderer for both video and audio in Mac. Saying that, I personally feel that custom audio and video drivers should just have the pertinent files in the sample, the rest being the default. So in this sample having Video capturing code like OTMTLVideoRenderer etc.. (same goes for the Basic app) makes the sample feels bulky and code heavy to implement.
> 
> Trying to follow the iOS samples file organization/exposure and making it feel the same for Mac..

WDYT, @rktalusani ?

**Comment by rktalusani** [comment]
right now Mac SDK is a low level C SDK so there is no default renderer. So we need the renderer files as part of the project.

**Comment by v-kpheng** [comment]
> right now Mac SDK is a low level C SDK so there is no default renderer. So we need the renderer files as part of the project.

your thoughts, @IGitGotIt ?

**Comment by IGitGotIt** [comment]
> > right now Mac SDK is a low level C SDK so there is no default renderer. So we need the renderer files as part of the project.
> 
> your thoughts, @IGitGotIt ?

We need to create a default renderer just like we have a `OTKMacDefaultVideoCapturer` and make it part of the SDK. This is future work.. so I am ok with the sample as it is.

**Comment by v-kpheng** [comment]
Merging, since @chetanvangadiTokbox approved.

**Pull request merged**
